### ISSUE TITLE
APK Permissions READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by ashleydb** [SideQuestVR/SideQuest#119] opened 2021-05-15 05:03 UTC
I'm adding some emulators as APKs via SideQuest to a Quest 1 and a Quest 2. Everything works fine but when booting the APKs (via Oculus TV app) they say they need the READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions set. If I set them via an adb command, things seem to work. For example, Retroarch:

adb shell pm grant com.retroarch.aarch64 android.permission.READ_EXTERNAL_STORAGE adb shell pm grant com.retroarch.aarch64 android.permission.WRITE_EXTERNAL_STORAGE

But then I noticed there is an option to do this within SideQuest by seeing the list of installed APKs, clicking the settings icon next to the APK name and toggling the permission switches. That seems faster/easier so I try that. However, whatever that does just breaks the APKs completely. Now trying to book them just goes right to am "Oops, something went wrong error". This doesn't seem to be recoverable, since uninstalling the APKs and reinstalling doesn't help at all and leaves me in that state.

So 1) what does that option in SideQuest actually do? 2) how can I reverse that? 3) can that bug be fixed please?

Tried this with both v0.10.20 and v.0.10.21

**Comment by sidequestlegend** [comment] 2021-08-12 12:36
Hey! So sorry for the delayed response, we were moving country. 

1) SideQuest runs the following:
`adb shell pm [revoke|grant] com.example.app_name android.permission.WRITE_EXTERNAL_STORAGE` 
2) The command will either grant or revoke the permission. Im not sure how this could be reversed any other way. 
3) I will test this out today and see if i can reproduce, but since SideQuest is running the same command that you are here could this be a red herring? Could there be another issue here?

I will report back after some testing.

**Comment by sidequestlegend** [comment] 2022-08-01 11:19
OK this has been overhaulled and appears to be working again now, fixed in the next release.

**Closed by sidequestlegend** 2022-08-01 11:19 UTC
Labels: bug, analysis needed, underway
